### ISSUE TITLE
Cannot find Content Provider

### ISSUE THREAD

**Issue by leo-neon** [zhgwu/shared_preferences_content_provider#1]
I always get 
java.lang.IllegalArgumentException: Unknown URI com.zhgwu.shared_preferences_content_provider.SharedPreferencesContentProvider

The provider is declared in Android Manifest of host application like so. Followed the steps in README. Am I doing something wrong?

**Comment by zhgwu** [comment]
> I always get java.lang.IllegalArgumentException: Unknown URI com.zhgwu.shared_preferences_content_provider.SharedPreferencesContentProvider
> 
> The provider is declared in Android Manifest of host application like so. Followed the steps in README. Am I doing something wrong?

flutter pub get
and try rebuild again.
