### ISSUE TITLE
app freezes on SharedPreferencesContentProvider.init

### ISSUE THREAD

**Issue by Alii-isk** [zhgwu/shared_preferences_content_provider#2]
when i try to init in `main.dart` the SharedPreferencesContentProvider the app freezes
`
 await SharedPreferencesContentProvider.init(
      providerAuthority:
          'com.zhgwu.shared_preferences_content_provider.example', //authority provider in AndroidManifest.xml
    );
`

**Comment by Alii-isk** [comment]
after some debugging i found out that awaiting `SharedPreferencesContentProvider.init` future never finishes.
so i just call SharedPreferencesContentProvider.init(...) without await

**Comment by zhgwu** [comment]
> after some debugging i found out that awaiting `SharedPreferencesContentProvider.init` future never finishes. so i just call SharedPreferencesContentProvider.init(...) without await

Thanks for your contribution, I fixed it in version 0.0.3
