### ISSUE TITLE
Proposal : listen for data updated

### ISSUE THREAD

**Issue by Alii-isk** [zhgwu/shared_preferences_content_provider#3]
Hi, thank u so much for the plug-in, 🥰
Would it be possible to implement `onChanged` and `notifyConsumers`, to notify for any update,

Currently I use dart stream in a loop and check for updates every 2 seconds and I think it would be much easier to add a listener 👂 in consumer app,

**Comment by zhgwu** [comment]
> Hi, thank u so much for the plug-in, 🥰 Would it be possible to implement `onChanged` and `notifyConsumers`, to notify for any update,
> 
> Currently I use dart stream in a loop and check for updates every 2 seconds and I think it would be much easier to add a listener 👂 in consumer app,

Thanks for your idea, it's really helpful. I added it in version 0.0.4. It will be available today.

**Comment by Alii-isk** [comment]
> > Hi, thank u so much for the plug-in, 🥰 Would it be possible to implement `onChanged` and `notifyConsumers`, to notify for any update,
> > Currently I use dart stream in a loop and check for updates every 2 seconds and I think it would be much easier to add a listener 👂 in consumer app,
> 
> Thanks for your idea, it's really helpful. I added it in version 0.0.4. It will be available today.

wow thank u ❤❤💗 i am still be using it on my app before publishing
